### ISSUE TITLE
long module could not be loaded

### ISSUE THREAD

**Issue by jnszkr** [quintanar401/connect-kdb-q#1]
hi,
i found an issue with node v5.10.0 on ubuntu. module Long in c.coffee could not be loaded because it was written with capital letter.

otherwise this is very cool :+1:

**Comment by quintanar401** [comment]
Hmm, indeed it is 'long', not sure why it did work before. I'll add a fix, thanks.

**Comment by quintanar401** [comment]
Fixed in 0.3.2
