### ISSUE TITLE
Can we move Query Results to bottom Dock?

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#12]
In regards to new Docks feature in 1.17:
http://blog.atom.io/2017/05/23/docks-deep-dive.html

Query Results can be manually dragged into the Dock, but would be nice if it appears there by default.

Not a critical feature by any means, but it's a nice to have. If you don't have time to implement, I can try a PR, although am very new at Atom dev.

Thanks!

**Comment by quintanar401** [comment]
Yes, it looks nice. You can try to add it - it is not that hard, it is very similar to the existing functionality. There is one issue (or was) - an editor (query view) didn't want to be inserted and I had to add stub functions like getTitle and etc. Maybe now it will work as is.

If there is some issue, i'll help

**Comment by quintanar401** [comment]
dock is added as an option
