### ISSUE TITLE
Query Results not scrollable after updating to Atom 1.19

### ISSUE THREAD

**Issue by joel23888** [quintanar401/connect-kdb-q#15]
I am running Windows 7 64-bit. Atom automatically updated from 1.18 to 1.19 today. In Atom 1.19 when I ran a query on kdb the result returns as normal but Query Results is not scrollable with the mouse or the keyboard. When I reverted to Atom 1.18 it returned to being scrollable.

**Comment by EdrinP** [comment]
Having the same issue.  Likely due to changes mentioned in #14

**Comment by EdrinP** [comment]
Possibly related issue: The Connect to a Server text box won't accept Enter key.

**Comment by quintanar401** [comment]
No, it is something else. Can't figure it out right away. One issue -  you can't set the font size on the view as before...

**Comment by quintanar401** [comment]
Well, it is not my bug I think. Again buildTextEditor() function is broken somehow - I have the same issue when I just add a new editor to a new pane without any modifications.

**Comment by joel23888** [comment]
I am only seeing this issue in Query Results, not in other editor tabs. I would add I can get the cursor to move around normally in Query Results, as indicated by the cursor position coordinates. The issue is just the pane not scrolling with it. I have rolled back to the previous version of Atom in the meantime.

**Comment by quintanar401** [comment]
Yes, this 

atom.workspace.getActivePane().addItem(atom.workspace.buildTextEditor())

leads to the same result so there is something wrong with this func.

**Comment by joel23888** [comment]
I am guessing that this is probably a regression linked to the re-implementation of textBuffer referred to in #14. Not really my area of expertise but I think it might still need some change in `connect-kdb-q` to support the new implementation.

**Comment by quintanar401** [comment]
Fixed it. It requires autoHight: false in buildTextEditor. Fonts are fixed as well - need to call a recalc of dimensions.

Keyboard issue is unrelated to 1.19 but it is fixed too. Down arrow will always work  now.

**Comment by joel23888** [comment]
Thanks, working for me in 1.19.
