### ISSUE TITLE
it has conflict with hydrogen. when hydrogen is installed, this package is not functioning at all. I am using Windows 10.

### ISSUE THREAD

**Issue by ghlian** [quintanar401/connect-kdb-q#17]

**Comment by quintanar401** [comment]
It redefines ctr-enter to itself. You should either change this key binding for kdb-connect or hydrogen to something else. 

The easiest way is to duplicate the Q definition in your key config (see File menu). It will be loaded after hydrogen and as it has a filter for the Q grammar it will not interfere with hydrogen. Copy the following into key cfg and restart atom:
```
'atom-workspace atom-text-editor[data-grammar="source q"]':
  'ctrl-enter': 'connect-kdb-q:exec-line'
```
