### ISSUE TITLE
Atom will "block" when return a huge table

### ISSUE THREAD

**Issue by cheduo** [quintanar401/connect-kdb-q#18]
Hi quintanar401,

Thanks for your excellent tool, connect-kdb-q; I use it a lot in my daily work.

Currently I find a small problem in using this package:
  I need to deal with huge table in my work, but when I query a huge table in Atom, it may "freeze" the editor, for example:
  q) tab /tab is a huge table

There's no calculation behind, but it take quite look time to return the result, some time it just crashes Atom.

I think in this case (for the huge table), it doesn't make sense in returning entire table, maybe we could just return first 10,000 lines of table. I could hack it in Q server in modifying .z.pg. 

But I wonder whether we could limit the size of the return table in package size?
Thanks,

**Comment by quintanar401** [comment]
Hi, I've added limitResSize setting (1G by def). Msgs will be dropped and incoming data ignored if their size is more than this value.

**Comment by cheduo** [comment]
That's great ! Thanks
