### ISSUE TITLE
Allow multiple q connections from same file

### ISSUE THREAD

**Issue by joel23888** [quintanar401/connect-kdb-q#19]
One use case I have is within one q file I need to run different lines (or blocks) of code on different q processes, some which cannot be connected to each other at the q level (eg development and production environments). I thought it may be useful to allow one line or block of code to point to one q process, and another piece code to point to another q process. For example:

Workflow:
* Create new q file
* Connect to a q process (`qserver1`)
* Enter some q code in the file (`qcode1`) and run it on `qserver1`
* Enter some more q code in the same file (`qcode2`), and while the cursor is in the line (or with selected text for a block) open a connection to another q process (`qserver2`) and run
* Now `qcode1` would be associated with `qserver1` and `qcode2` associated with `qserver2`. Further q code would be associated with `qserver2` until I make a new connection to another q process
* `qcode1` could be switched to another q process by selecting it (or positioning the cursor in the line) and connecting to another q process
* As the user moved the cursor between `qcode1` and `qcode2` etc the status bar would update to reflect the active q server

Let me know if above is useful or anything is not clear. Happy to provide more details on the use case.

**Comment by quintanar401** [comment]
Currently it is possible to connect to several processes, to switch between them you need to click the grin name below. I guess it is possible to add a function that can be associated with a hot key to switch between connections. To remember a server for each line seems an overkill.
