### ISSUE TITLE
Fails on null datetimes

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#2]
To reproduce, run Q expression:  0Nz
Silently fails with nothing printed in query results tab. Also fails if 0Nz is anywhere in results (list, table, etc). Works with a non-null datetime (ex: .z.z). Works with most other null types tested.
Atom version 1.7.1, connect-kdb-q version 0.3.2

**Comment by quintanar401** [comment]
Null or Infinite floats/reals were not correctly processed (only datetime crashed). Thanks. Fixed in 0.3.3
