### ISSUE TITLE
Connection dropping

### ISSUE THREAD

**Issue by joel23888** [quintanar401/connect-kdb-q#22]
I have had connections from connect-kdb-q to a remote q process drop after some idle time. The corporate firewall I have to be behind does this after 30 minutes. Is there any way to configure connect-kdb-q so it will send a TCP keepalive packet every x minutes?

**Comment by quintanar401** [comment]
Currently no. Try to add 

@client.setKeepAlive(true, 1000)

in onConn function (line 611) in c.coffee

to see if it helps.

**Comment by joel23888** [comment]
My network team configured this on the server side, but I did also try your suggestion prior to this and it seemed to work.
