### ISSUE TITLE
Atom 1.25: All queries failing with Uncaught TypeError: Path must be a string

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#23]
After 1.25 update, getting below error on any interaction in connect-kdb-q  (exec query, connect to server, etc)

Uncaught TypeError: Path must be a string. Received undefined

**Comment by joel23888** [comment]
I am having the same issue

**Comment by lynx-ilya** [comment]
same here :(

**Comment by EdrinP** [comment]
Looking into a fix.  It appears atom.config.configDirPath in servers.coffee is gone in 1.25.

**Comment by joel23888** [comment]
I am not sure if this is obvious or helps anybody, but I was considering rolling back to the previous Atom version and I realized it was actually kept in the installation directory alongside the latest version. If you run the Atom executable from there you can 'roll back' without much effort while this is being fixed.

**Comment by quintanar401** [comment]
Thanks, I merged the pull request. 0.4.11 should resolve this issue
