### ISSUE TITLE
is it possible to display C shared objects in atom?

### ISSUE THREAD

**Issue by cheduo** [quintanar401/connect-kdb-q#25]
Hello, 
Is it possible to display dynamic loaded function (C shared objects in atom)?
I'm playing with p.q (embedPy), it seems one can not display namespace .p properly in atom:
`\l p.q`
in terminal:
```
q).p
eval    | {[f;x]r:wrap f x 0;$[count x:1_x;.[;x];]r}[code]enlist
e       | {$["def"~3#x;$[x[3]in"<*>";ei 3;eo];"class"~5#x;$[x[5]in"*>";ei 5;e..
py2q    | code
q2py    | code
get     | {[f;x]r:wrap f x 0;$[count x:1_x;.[;x];]r}[code]enlist
set     | {[f;x;y]f[x]unwrap y;}[code]
import  | {[f;x]r:wrap f x 0;$[count x:1_x;.[;x];]r}[code]enlist
getattr | code
...
```
in atom:
```
Q: .p
'type
```
Thanks

**Comment by quintanar401** [comment]
This is not related to Atom - it is Q IPC issue. If you try to request .p from another Q process you'll see the same error. I don't think I can do anything here - I would have to modify the original query.

**Comment by cheduo** [comment]
Exactly! It's due to the problem of IPC. But strangely it seems jupyterq can display it properly:

![image](https://user-images.githubusercontent.com/16296579/40459531-7901c6b4-5f34-11e8-8d71-e6a1efb38ff3.png)

It's a bit painful to use embedPy in atom, if we couldn't display it properly. Maybe I could make some modification on .z.pg to filter dynamic load type.

**Comment by quintanar401** [comment]
I guess all data goes through embedPy. It is like if you would modify .z.pg to sanitize the result.

**Comment by cheduo** [comment]
OK, thanks !
