### ISSUE TITLE
Possible to clear the query results window every time a query is run

### ISSUE THREAD

**Issue by AlexGCWong** [quintanar401/connect-kdb-q#26]
Hi,

Is it possible to have it such that every time a query is executed, the query result window is cleared? This is fairly useful during debugging.

Cheers

**Comment by quintanar401** [comment]
Hi,

I've added CLEAR txt cmd as it looks like it is a temporary mode and it would be cumbersome to change a setting every time. 

Add CLEAR as the first line in the result view and it will be cleared on every query. Once you don't need it anymore remove CLEAR.

**Comment by AlexGCWong** [comment]
Ahh perfect. That sounds like a sound solution. Thank you for implementing this so quickly!
