### ISSUE TITLE
find definition in menu as shortcut

### ISSUE THREAD

**Issue by MaxHoefl** [quintanar401/connect-kdb-q#28]
Hi,

in `menus/connect-kdb-q.cson` I can see the KDB-Q menu entries 

- Connect to a server
- Exec Line
- Exec selection

but I cannot find "Find definition" and "Find reference" which are also part of the KDB-Q menu which confuses me a bit.

My goal is to add a shortcut to "Find definition" and "Find reference" in `keymaps/connect-kdb-q.cson` but I guess there would have to be a new event to be registered in `connect-kdb-q`

Thanks

**Comment by quintanar401** [comment]
Hi,

This is because Find definition and reference are in autocomplete-kdb-q.

You can add any shortcut in your main cfg I think using the cmd name.

WBR, Andrey Kozyrev.

2018-07-23 13:29 GMT+03:00 MaxHoefl <notifications@github.com>:
