### ISSUE TITLE
Fails to display certain dictionaries

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#3]
For a dictionary where the key is a table, but the value isn't (not a typical situation, but can happen), there's a silent failure and nothing displays on Query Results.
For example:  ([]a:til 3)!til 3

**Comment by quintanar401** [comment]
Yes, there is a problem, thanks. I'll try to fix it this week.

**Comment by quintanar401** [comment]
Fixed both table!list and list!table
