### ISSUE TITLE
Minor issue in displaying nested sym dictionaries

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#4]
Run this:
`(`a`b)!(1; (1#`c)!1#`d)`

Displays result:
`a|1`
`b|enlist c!enlist d`

Would be nice if the last line was either of the following:
`b|(enlist `c)!enlist `d`
`b| (,`c)!,`d`   (this is what the q prompt displays)

**Comment by quintanar401** [comment]
added () for 1 element keys
, vs enlist can be customized I guess but probably there is other k-like output...
