### ISSUE TITLE
Query Results editor broken with Atom 1.11.0 update

### ISSUE THREAD

**Issue by EdrinP** [quintanar401/connect-kdb-q#5]
After Atom 1.11.0 update (and also 1.11.1),  upon executing a query the bottom pane is split but the Query Results editor itself is not visible.

**Comment by quintanar401** [comment]
Yes, they considerably changed the way the new editors should be created - not possible to use workspace.buildTextEditor and then add this editor to a pane. I've managed to fix it I think. Please check.

**Comment by EdrinP** [comment]
Your fix is working, thanks for the quick resolution!

**Comment by quintanar401** [comment]
It is actually atom's bug, I'll revert back when it is fixed.

**Comment by EdrinP** [comment]
Looks like 1.11.2 has fixed this, feel free to revert your changes
