### ISSUE TITLE
Timestamp display

### ISSUE THREAD

**Issue by joel23888** [quintanar401/connect-kdb-q#7]
Timestamps are displayed by `connect-kdb-q` using a 'T' to delimit the date from the time part, but `q` uses 'D':
```
(`SUCCESS; "kdb+ PROD1 hdb"; 6ms; `timestamp$)
2016.12.16T15:00:00.000000000
Q: 2016.12.16D15:00:00.000000000
```

Changing it to 'D' would be more consistent with kdb and make testing of code easier by being able to paste outputs from Atom directly to other places.

I think this could be handled by modifying https://github.com/quintanar401/connect-kdb-q/blob/master/lib/c.coffee#L177 to replace 'T' with 'D'. Unfortunately I cannot push to github or publish from where I am based, so it makes it difficult for me to fix this.

**Comment by quintanar401** [comment]
Thanks, fixed in 0.4.4
